# Generated by Django 4.2 on 2024-04-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is super user')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('secondEmail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Secondary email')),
                ('first_name', models.CharField(max_length=50, verbose_name='Fisrt name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('tel', models.CharField(max_length=9, verbose_name='Phone number')),
                ('country', models.CharField(max_length=20, verbose_name='Country')),
                ('region', models.CharField(max_length=20, verbose_name='Region')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('zipCode', models.IntegerField(verbose_name='Zip code')),
                ('username', models.CharField(max_length=10, verbose_name='User name')),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='user/profileImages')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
