# Generated by Django 4.2 on 2024-04-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(max_length=20, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.CharField(max_length=20, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel',
            field=models.CharField(max_length=9, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=10, null=True, verbose_name='User name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='zipCode',
            field=models.IntegerField(null=True, verbose_name='Zip code'),
        ),
    ]
