# Generated by Django 4.2 on 2024-04-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_address_alter_customuser_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'get_latest_by': 'date_joined', 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='secondEmail',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Secondary email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel',
            field=models.CharField(max_length=9, null=True, unique=True, verbose_name='Phone number'),
        ),
    ]
